### ISSUE TITLE
Support blobs in MEV-Boost/Relay/Builder forks

### ISSUE THREAD

**Issue by thedevbirb** [chainbound/bolt#113]
There is already an issue to support blobs in the Bolt sidecar: #105. However, some work is also needed in the rest of the pipeline to make sure the builder is able to create bid with pre-confirmed blob transaction.

Ideally, this should be done by not making any breaking change to the specs.

```[tasklist]
### Tasks
- [ ] Support blobs in MEV-Boost fork
- [ ] Support blobs in Flashbots' relay fork
- [ ] Support blobs in Flashbots' builder fork
```
