### ISSUE TITLE
Sidecar: Telemetry & Metrics 

### ISSUE THREAD

**Issue by merklefruit** [chainbound/bolt#116]
```[tasklist]
### Bolt-sidecar telemetry
- [x] Review the level of existing traces, and change or remove any unnecessary ones
- [x] Add the option to instrument a Prometheus listener to collect useful metrics
- [x] Add meaningful metrics to the sidecar, including health-checks, alerts, and important events
- [x] Infra: create a default Grafana dashboard to visualize the sidecar status
- [ ] (optional) Add the option to instrument a log collector such as a remote Loki instance
- [ ] (optional) Add the option to log to a file in JSON to support external log collectors like Promtail
```

**Comment by thedevbirb** [comment]
I'd love to take this, since I'm quite unfamiliar with these tools and it'd be a great way to learn them

**Comment by thedevbirb** [comment]
Since we're now taking this milestone I will approach this soon. @merklefruit wdyt if I take inspiration from Bolt RPC, regarding telemetry? I'm think about this: https://github.com/chainbound/bolt-rpc/blob/main/src/telemetry/mod.rs.

**Comment by merklefruit** [comment]
Sure, that sounds like a good starting point. For the sidecar we'd likely skip Axiom though

**Comment by namn-grg** [comment]
Sounds good! (I think its more efficient if single person does the whole issue so unassigning myself)
