### ISSUE TITLE
tracking(holesky): smart contracts

### ISSUE THREAD

**Issue by merklefruit** [chainbound/bolt#206]
```[tasklist]
### Validator registry contract
- [x] Redesign registry with Validator authentication (`BoltValidators`) and Bolt-specific logic (`BoltManager`)
- [x] Add the ability to authenticate with BLS + SSZ proofs (deprecated) as a validator
- [x] Add ability to register by simply saving the public keys in a mapping (with no BLS or SSZ checks)
- [x] Add unit tests
- [x] Add extensive documentation & registration guide
```

```[tasklist]
### Restaking integrations: Symbiotic
- [x] Understand symbiotic abstractions to support external restaked collateral
- [x] Add basic support for symbiotic vaults & operators
- [x] Add opt-in logic & stake flow
- [x] Add opt-out logic & unstake flow -> mostly left to Symbiotic vaults
- [x] Add slashing flow
- [x] Test symbiotic integration with `BoltManager` via unit tests
- [x] Add unit tests with Symbiotic's foundry fixture
- [ ] Add extensive documentation and integration guide
```

```[tasklist]
### Restaking integrations: Eigenlayer
- [x] Understand Eigenlayer abstractions and how they differ from Symbiotic
- [x] Add basic support for eigenlayer pods & operators
- [x] Add opt-in logic & stake flow
- [x] Add opt-out logic & unstake flow
- [x] Add slashing flow
- [x] Test eigenlayer integration via unit tests
- [x] Add unit tests with Eigenlayer's foundry fixture
- [ ] Add extensive documentation and integration guide
```

```[tasklist]
### Restaking integrations: Proxy + Adapters
- [x] Design a restaking interface abstraction to remove logic in `BoltManager` and add any restaking support behind adapter proxy contracts
- [x] Implement a generic restaking interface
- [x] Implement the Symbiotic protocol logic by porting it over from `BoltManager`
- [x] Implement the Eigenlayer protocol logic by porting it over from `BoltManager`
```

```[tasklist]
### Challenger
- [x] decide if we should do a clean rewrite or use the existing old impl
- [x] Spike out what removing Relic entails (ref #36)
- [x] Rewrite challenge resolution logic with MPT proofs
- [ ] https://github.com/chainbound/bolt/issues/36
- [x] add challenge opening unit tests
- [x] add challenge resolution happy case tests
- [x] add challenge resolution pathological case tests
```

### Extra

- A further iteration of the registry contract will include a proxy design with Root+Sub registries to handle protocol-specific opt-ins. This is out of scope for the current cycle.
- #237 
- #233 

### Meta

- #95 
- #196
- #199 #16
