### ISSUE TITLE
Tracking: update constraints-API in PBS

### ISSUE THREAD

**Issue by mempirate** [chainbound/bolt#209]
## Context
This issue tracks the implementation of the new constraints API across the PBS pipeline. Note that we can implement Blob Express Lane in the relay & builder.

```[tasklist]
## Bolt Sidecar
- [ ] #208
- [ ] https://github.com/chainbound/bolt/pull/225
- [ ] https://github.com/chainbound/bolt/issues/230
- [ ] https://github.com/chainbound/bolt/issues/290
- [ ] https://github.com/chainbound/bolt/issues/283
```

@merklefruit can work on this:
```[tasklist]
## Flashbots Builder
- [x] Update types
- [x] Remove authentication header (not needed according to the relays)
- [x] Update constraints stream (new format & types)
- [x] Nit: get rid of "preconf" wording everywhere, change to constraints
- [x] Remove Bolt demo events
- [x] Add relevant log lines
```

@namn-grg is working on this:
```[tasklist]
## Helix
- [x] Implement proposer-facing [constraints-API](https://chainbound.github.io/bolt-docs/api/builder)
- [x] Implement builder-facing [constraints-API](https://chainbound.github.io/bolt-docs/api/relay)
- [x] Verify BLS signatures on `SignedConstraints` (will be signed with commit-boost signing domain!)
- [x] Verify authorized BLS pubkey on `SignedConstraints`!
```
