### ISSUE TITLE
Tracking: Improve node operator testing setup

### ISSUE THREAD

**Issue by merklefruit** [chainbound/bolt#236]
For our new Holesky deployment, we need to improve the UX for node operators wishing to opt-in.

- [x] #159 
- [x] update `bolt-client` to work seamlessly for NOs to target their own validator indexes to test by themselves
- [x] create a better UI for checking the status of Bolt software - this could maybe be a Grafana dashboard or something else for NOs to easily see what's going on in the Bolt sidecar and all Bolt-related software. 
- [x] create and maintain documentation about the opt-in process in light of our new registry setup

**Comment by merklefruit** [comment]
Closed in #296
