### ISSUE TITLE
[tracking] smart contracts (V1)

### ISSUE THREAD

**Issue by merklefruit** [chainbound/bolt#259]
```[tasklist]
### Remaining tasks
- [ ] https://github.com/chainbound/bolt/issues/248
- [ ] https://github.com/chainbound/bolt/issues/238
- [ ] https://github.com/chainbound/bolt/issues/237
- [ ] https://github.com/chainbound/bolt/issues/219
- [ ] https://github.com/chainbound/bolt/issues/244
- [ ] https://github.com/chainbound/bolt/issues/243
- [ ] https://github.com/chainbound/bolt/issues/252
- [ ] https://github.com/chainbound/bolt/issues/273
```
