### ISSUE TITLE
Kurtosis devnet scenarios

### ISSUE THREAD

**Issue by mempirate** [chainbound/bolt#29]
## Context
We want to showcase Bolt functionality in a couple of happy and not-so-happy scenarios. This issue will track the progress of each.

```[tasklist]
## Scenarios
- [x] Succesful inclusion preconfirmation through PBS [PRIORITY]
- [x] Succesful inclusion preconfirmation with builder / relay fault (fallback building) [PRIORITY]
- [ ] Inclusion preconf commitment breach with successful challenge (safety fault)
- [ ] Inclusion preconf commitment breach with liveness fault and unsuccessful challenge
```

**Comment by merklefruit** [comment]
Closing priority 2 with #97!
