### ISSUE TITLE
`bolt-cli` revamp

### ISSUE THREAD

**Issue by mempirate** [chainbound/bolt#307]
## Context
Because we'll add a lot more functionality to the CLI, we should rename the `bolt-delegations-cli` to just `bolt-cli` (with binary command just being `bolt`). We'll also want to leverage it for the following:

```[tasklist]
# Commands
- [x] Integrate with DIRK
- [x] Querying Bolt-related information on-chain
- [x] send transactions (replace `bolt-client` and `bolt-kurtosis-client`)
- [ ] https://github.com/chainbound/bolt/issues/365
- [ ] https://github.com/chainbound/bolt/issues/392
- [x] Easily register operators (replace foundry scripts + better configuration)
```
