### ISSUE TITLE
tracking(sidecar): remove leftover `TODO` comments

### ISSUE THREAD

**Issue by merklefruit** [chainbound/bolt#359]
```[tasklist]
### Open TODOs
- [x] [Driver: match when we have more request types](https://github.com/chainbound/bolt/blob/lore/feat/holesky-launch/bolt-sidecar/src/driver.rs#L318)
- [x] [Driver: fix retry logic, and move to separate task in constraints client](https://github.com/chainbound/bolt/blob/lore/feat/holesky-launch/bolt-sidecar/src/driver.rs#L407)
- [x] `primitives::*`: minor nits and SSZ-related implementation choices
- [x] [Config: parse validator indexes from a file: Are we still using these? if so, add this, else remove completely](https://github.com/chainbound/bolt/blob/lore/feat/holesky-launch/bolt-sidecar/src/config/validator_indexes.rs#L26)
- [x] [StateFetcher: add block number in params](https://github.com/chainbound/bolt/blob/lore/feat/holesky-launch/bolt-sidecar/src/state/fetcher.rs#L97)
- [ ] [ExecutionState: add a way to add validation params via CLI](https://github.com/chainbound/bolt/blob/lore/feat/holesky-launch/bolt-sidecar/src/state/execution.rs#L211)
- [ ] [ExecutionState: also validate more conditions from Reth](https://github.com/chainbound/bolt/blob/lore/feat/holesky-launch/bolt-sidecar/src/state/execution.rs#L231)
- [ ] [ConsensusState: integrate onchain registry in request validation](https://github.com/chainbound/bolt/blob/lore/feat/holesky-launch/bolt-sidecar/src/state/consensus.rs#L107)
- [ ] [ConsensusState: check if the sidecar is scheduled to propose (?)](https://github.com/chainbound/bolt/blob/lore/feat/holesky-launch/bolt-sidecar/src/state/consensus.rs#L103)
- [ ] [Chainio: related to https://github.com/chainbound/bolt/issues/343](https://github.com/chainbound/bolt/blob/lore/feat/holesky-launch/bolt-sidecar/src/chain_io/manager.rs#L36)
- [ ] [Chainio: performance nerdsnipe?](https://github.com/chainbound/bolt/blob/lore/feat/holesky-launch/bolt-sidecar/src/chain_io/manager.rs#L71)
- [ ] [Chainio: check if this can be cleaned up a little](https://github.com/chainbound/bolt/blob/lore/feat/holesky-launch/bolt-sidecar/src/chain_io/manager.rs#L84)
- [ ] [Builder API: determine adequate timeout value](https://github.com/chainbound/bolt/blob/lore/feat/holesky-launch/bolt-sidecar/src/api/builder.rs#L37)
- [ ] [Builder API: this should be removed as it's not done in the sidecar anymore, IMO](https://github.com/chainbound/bolt/blob/lore/feat/holesky-launch/bolt-sidecar/src/api/builder.rs#L89)
- [ ] [Builder API: handle get_header failure more clearly](https://github.com/chainbound/bolt/blob/lore/feat/holesky-launch/bolt-sidecar/src/api/builder.rs#L139)
- [ ] [Builder API: handle get_payload failure more clearly](https://github.com/chainbound/bolt/blob/lore/feat/holesky-launch/bolt-sidecar/src/api/builder.rs#L198)
- [ ] [Builder API: add some more sanity checks when checking for local payload integrity](https://github.com/chainbound/bolt/blob/lore/feat/holesky-launch/bolt-sidecar/src/api/builder.rs#L391)
```
