### ISSUE TITLE
Firewall delegation support

### ISSUE THREAD

**Issue by mempirate** [chainbound/bolt#518]
Tracking issue for firewall delegation support in the sidecar. 

> Firewall delegation allows proposers to configure multiple “firewalls” to outsource filtering and pricing inclusion requests. It gets rid of the requirement for proposers to expose any public endpoints, but rather subscribe to any of the delegated firewalls for a stream of filtered and priced inclusion requests. Proposers running the sidecar are still responsible for signing commitments, submitting & verifying constraints, and building fallback blocks. They remain the single source of truth for valid commitments, which means we don’t have to deal with issues like split-brain and subjectivity. At the same time, the heavy lifting is outsourced to third parties with minimal added trust assumptions.

```[tasklist]
# Tasks
- [x] CLI flag `--firewall-rpc` for 1 or more values
- [x] Make commitments RPC optional and disable by default if `--firewall-rpc` is set
- [x] Initiate (durable) WebSocket connections with firewalls on `/api/v1/firewall_stream`
- [x] Multiplex incoming messages over single stream which yields origin as `oneshot::Sender` along with messages (for replies)
- [x] Wrap current commitment validation logic with with req/resp matching logic on uuids
```

**Comment by merklefruit** [comment]
Related: #390
