### ISSUE TITLE
[tracking] devnet integration in CI

### ISSUE THREAD

**Issue by thedevbirb** [chainbound/bolt#547]
The current CI features mainly unit tests of the bolt sidecar, while e2e tests are manually done by spinning up the devnet provided by the Ethereum package.
As we're approaching mainnet and more and more people are running this software, security and testing are a top priority. Therefore a robust suite of E2E tests running in CI is essential.
This issue tracks some of the required steps to achieve so.

```[tasklist]
### Remaining tasks
- [ ] Add GitHub action to install the kurtosis CLI. Reference: https://github.com/ethpandaops/ethereum-package/blob/a182f3039b91c15cde5b0d0967666d336a9629ac/.github/actions/kurtosis-install/action.yaml
- [ ] Study the `assertoor` service of the Ethereum Package and outline in a document how can we leverage it.
- [ ] Fix CI on our Ethereum Package fork
- [ ] Run a per-PR workflow against `unstable` that spins up the devnet, leveraging the assertoor. Reference: https://github.com/ethpandaops/ethereum-package/blob/a182f3039b91c15cde5b0d0967666d336a9629ac/.github/workflows/per-pr.yml
```

Since we're running a very old fork of such package it'd be great to update it. However it requires an `rbuilder` fork supporting the Constraints-API since the older Geth builder has been deprecated.
